### ISSUE TITLE
Add a develop image

### ISSUE THREAD

**Issue by evanzhang87** [mozillazg/ptcpdump#126]
Hello, I'd like to do something, but it's hard to prepare a develop environment, especially in a internel network.

**Comment by mozillazg** [comment]
What type of image do you mean? A Vagrant image or a docker image?

**Comment by evanzhang87** [comment]
Docker image, which I can use in Makefile

**Comment by mozillazg** [comment]
@evanzhang87 The docker image was added. Please take a look at the README.
