### ISSUE TITLE
Can't execute ptcpdump binary file

### ISSUE THREAD

**Issue by hengyoush** [mozillazg/ptcpdump#142]
**Describe the bug**
i download the latest release 0.22.0 and execute it, but error happens:
```
 ./ptcpdump 
bash: ./ptcpdump: cannot execute binary file: Exec format error
```
my kernel version is:
```
Linux VM-4-9-ubuntu 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**How to reproduce it**

**Expected behavior**

**Environment**

- ptcpdump version:

- OS:

- Kernel:

**Additional context**

**Comment by mozillazg** [comment]
@hengyoush Thanks for reporting. 

* Could you please provide the output of `file ./ptcpdump` ? 
* Could you please try again to run ptcpdump with docker ? 

```
docker run --privileged --rm -it --pid=host -v /sys/kernel/debug:/sys/kernel/debug \
            -v `pwd`:/app ubuntu:22.04 /app/ptcpdump --version
```
