### ISSUE TITLE
no comment info in pcpa file

### ISSUE THREAD

**Issue by wangzhankun** [mozillazg/ptcpdump#163]
**Describe the bug**

When the output is stdout, ptcpdump can show the comment info. But when try to output to pcap file, I cannnot find comment info in wireshark.
```sh
 ./ptcpdump -i eth0 -v # stdout
 ./ptcpdump -i eth0 -v -w test.pcap # to pcap file
```
<img width="1860" alt="image" src="https://github.com/user-attachments/assets/989fbf1d-ebdc-47a2-8050-5440468bf447">
<img width="913" alt="image" src="https://github.com/user-attachments/assets/0d157055-5b61-4666-b202-a3a002b6ffd8">

**Environment**

- ptcpdump version: ptcpdump version 0.24.0
libpcap version 1.10.5 (with TPACKET_V3)

- OS: PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel: 5.4.250-4-velinux1u1-amd64

**Additional context**

**Comment by mozillazg** [comment]
@wangzhankun Thanks for reporting. Only the pcapng format support comment. Please try again with pcapng file:

```
 ./ptcpdump -i eth0 -v -w test.pcapng
```
