### ISSUE TITLE
Filtering by container-id supports prefix matching with 12 or more characters.

### ISSUE THREAD

**Issue by hengyoush** [mozillazg/ptcpdump#217]
Currently ptcpdump only support filter by full-length container-id or 12-characters short id, but the `crictl ps` command display 13-characters id which can't be filtered successfully.

I think filtering by container-id supports prefix matching with 12 or more characters is needed, what do you think?

If possible, i can submit a pr.

**Comment by mozillazg** [comment]
@hengyoush Thanks for the suggestion! Feel free to send a pull request.
