### ISSUE TITLE
build for arm64 error 

### ISSUE THREAD

**Issue by uk0** [mozillazg/ptcpdump#40]
/home/parallels/Desktop/work/ptcpdump/bpf/ptcpdump.c:375:5: error: incomplete definition of type 'struct user_pt_regs'
int BPF_KPROBE(kprobe__security_sk_classify_flow, struct sock *sk) {
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./headers/bpf/bpf_tracing.h:817:20: note: expanded from macro 'BPF_KPROBE'
        return ____##name(___bpf_kprobe_args(args));                        \
                          ^~~~~~~~~~~~~~~~~~~~~~~~
./headers/bpf/bpf_tracing.h:797:41: note: expanded from macro '___bpf_kprobe_args'
#define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./headers/bpf/bpf_helpers.h:195:29: note: expanded from macro '___bpf_apply'
#define ___bpf_apply(fn, n) ___bpf_concat(fn, n)
                            ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
<scratch space>:101:1: note: expanded from here
___bpf_kprobe_args1
^
./headers/bpf/bpf_tracing.h:789:72: note: expanded from macro '___bpf_kprobe_args1'
#define ___bpf_kprobe_args1(x)          ___bpf_kprobe_args0(), (void *)PT_REGS_PARM1(ctx)
                                                                       ^~~~~~~~~~~~~~~~~~
./headers/bpf/bpf_tracing.h:485:44: note: expanded from macro 'PT_REGS_PARM1'
#define PT_REGS_PARM1(x) (__PT_REGS_CAST(x)->__PT_PARM1_REG)
                          ~~~~~~~~~~~~~~~~~^
/home/parallels/Desktop/work/ptcpdump/bpf/ptcpdump.c:375:5: note: forward declaration of 'struct user_pt_regs'
./headers/bpf/bpf_tracing.h:817:20: note: expanded from macro 'BPF_KPROBE'
        return ____##name(___bpf_kprobe_args(args));                        \
                          ^
./headers/bpf/bpf_tracing.h:797:41: note: expanded from macro '___bpf_kprobe_args'
#define ___bpf_kprobe_args(args...)     ___bpf_apply(___bpf_kprobe_args, ___bpf_narg(args))(args)
                                        ^
./headers/bpf/bpf_helpers.h:195:29: note: expanded from macro '___bpf_apply'
#define ___bpf_apply(fn, n) ___bpf_concat(fn, n)
                            ^
note: (skipping 2 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
./headers/bpf/bpf_tracing.h:789:72: note: expanded from macro '___bpf_kprobe_args1'
#define ___bpf_kprobe_args1(x)          ___bpf_kprobe_args0(), (void *)PT_REGS_PARM1(ctx)
                                                                       ^
./headers/bpf/bpf_tracing.h:485:27: note: expanded from macro 'PT_REGS_PARM1'
#define PT_REGS_PARM1(x) (__PT_REGS_CAST(x)->__PT_PARM1_REG)
                          ^
./headers/bpf/bpf_tracing.h:228:42: note: expanded from macro '__PT_REGS_CAST'
#define __PT_REGS_CAST(x) ((const struct user_pt_regs *)(x))
                                         ^
1 error generated.
Error: can't execute clang: exit status 1
exit status 1
bpf/bpf.go:18: running "go": exit status 1
make: *** [Makefile:61: build-bpf] Error 1
parallels@ubuntu-linux-22-04-desktop:~/Desktop/work/ptcpdump$ make 
make: Nothing to be done for 'libpcap'.
parallels@ubuntu-linux-22-04-desktop:~/Desktop/work/ptcpdump$ 


----


I use Apple（m2 max ） to build a virtual machine and use the current project. It cannot be compiled or used normally. Do you have any plans to support it? Thank you very much for your contribution.

**Comment by mozillazg** [comment]
> Do you have any plans to support it?

Yes. It is in the plan: https://github.com/mozillazg/ptcpdump/issues/25

**Comment by mozillazg** [comment]
@uk0 The latest version already support arm64. please check it.
